name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build APK
        run: flutter build apk --release-split-per-abi

      - name: Build IPA
        run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cp -R ../Runner.app Payload/
          cd ..
          zip -r app.ipa Payload

#   release:
#     runs-on: ubuntu-latest

#     needs: build

#     steps:
#       - name: Push to Releases
#         uses: ncipolto/release-action@v1
#         with:
#           artifacts: "build/app/outputs/apk/release/*, build/ios/iphoneos/app.ipa"
#           tag: v1.0.${{ github.run_number }}
#           token: ${{ secrets.TOKEN }}
